### ISSUE TITLE
Calling the .comments of a comments object

### ISSUE THREAD

**Issue by zfogg** [larryng/narwal#4]
I'm trying to build the full comment trees of a Reddit thread with Narwal. When I look at a comment object and try to find its subcomments with the .comments() method, that just returns a Listing object that contains only itself.

```
comment = myUser.submitted()[0].comments()[0]
comment.comments()[0] == comment # True

# You can keep going like this forever. It will always return the original comment object.
comment.comments()[0].comments()[0].comments()[0].comments()[0].comments()[0]
```

**Comment by larryng** [comment]
Comments to a comment are stored in comment.replies, as per Reddit API.  Calling .comments() is akin to viewing the comments page in Reddit.

**Comment by zfogg** [comment]
Oh I see. Well while I was trying to figure this out, I noticed the @mellort's API wrapper has an all_comments property on its Submission objects, which builds the entire comment tree. I've been using that and it's been working great. Is that implemented in Narwal?

**Comment by larryng** [comment]
No, it's not.  However, I actually wrote a simple implementation of all_comments() a few days ago, which you can find here:
https://github.com/larryng/reddit-iama-bot/blob/master/iama/utils.py#L23. It doesn't do any error checking though and it tries to grab all of the comments in succession, so it is susceptible to rate-limiting, especially since an /api/morechildren call is a POST.  I hope you find it useful though in implementing your own function, if you choose to do so.

As for implementing all_comments() in narwal, I'm not sure I want to do so. I intend to make/keep narwal functionally complete, while also keeping it "thin," i.e. just a simple, intuitive wrapper around reddit's API.

**Comment by zfogg** [comment]
Thanks for the link. Although that looks like a flat list.. I'm building the original tree data structure. My recursive tree class works fine in mellort's, so I'll probably take a stab at writing the function myself for narwal.

**Comment by zfogg** [comment]
actually I do see the branching recur in your function there, oops ;x
